{{- if and .Values.mode.base .Values.awsLoadBalancerController.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
      version: 1.12.x
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 10m
  releaseName: aws-load-balancer-controller
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    # clusterName: CLUSTER_NAME

    #serviceAccount:
    #  annotations:
    #    eks.amazonaws.com/role-arn: ROLE_ARN

    serviceMonitor:
      enabled: {{ .Values.monitoring.enabled }}
{{- end }}
