{{- if and .Values.manifests .Values.certManager.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: 1.17.x
  dependsOn:
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
  {{- end }}
  install:
    createNamespace: true
    crds: CreateReplace
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    disableWait: false
    remediation:
      retries: -1
  interval: 10m
  releaseName: cert-manager
  storageNamespace: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true

    prometheus:
      servicemonitor:
        enabled: true
{{- end }}