{{- if and .Values.manifests .Values.certManagerConfig.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager-config
      sourceRef:
        kind: HelmRepository
        name: getupcloud
      version: 0.2.x
  dependsOn:
    - name: cert-manager
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: cert-manager-config
  storageNamespace: cert-manager
  targetNamespace: cert-manager
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  values:
    ingress_class: {{ include "ingressClassName" . }}
    cluster_issuer_letsencrypt:
      enabled: true
    cluster_issuer_selfsigned:
      enabled: true
{{- end }}