{{- if and .Values.manifests .Values.externalSecrets.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: 0.9.x
  install:
    createNamespace: true
    crds: CreateReplace
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 10m
  releaseName: external-secrets
  storageNamespace: external-secrets
  targetNamespace: external-secrets
  values:
    serviceMonitor:
      enabled: true
      interval: 60s
{{- end }}
