{{- if and .Values.manifests .Values.flagger.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
      version: 1.41.x
  dependsOn:
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
  {{- end }}
  install:
    createNamespace: true
    crds: CreateReplace
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    disableWait: false
    remediation:
      retries: -1
  interval: 10m
  releaseName: flagger
{{- end }}
