{{- if and .Values.mode.base .Values.promtail.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 6.16.x
  dependsOn:
  {{- if .Values.loki.enabled }}
  - name: loki
  {{- end }}
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 10m
  releaseName: promtail
  storageNamespace: logging
  targetNamespace: logging
  values:
    configmap:
      enabled: true

    config:
      #clients:
      #- url: http://loki-gateway:80/loki/api/v1/push

      snippets:
        extraRelabelConfigs:
        # keep all kubernetes labels
        #- action: labelmap
        #  regex: __meta_kubernetes_pod_label_(.+)
        # remove hashing labels in order to decrease cardinality
        - action: labeldrop
          regex: __meta_kubernetes_pod_label_.*_hash

    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 64Mi

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: "25%"

    serviceMonitor:
      enabled: {{ .Values.monitoring.enabled }}
      interval: 60s

    #volumes:
    #- name: containers
    #  hostPath:
    #    path: /var/lib/containers
    #- name: docker
    #  hostPath:
    #    path: /var/lib/docker/containers
    #- name: pods
    #  hostPath:
    #    path: /var/log/pods
    ##
    ## OCI OKE
    ##
    ##- hostPath:
    #    path: /u01
    #  name: u01
    #
    #volumeMounts:
    #- name: containers
    #  mountPath: /var/lib/containers
    #  readOnly: true
    #- name: docker
    #  mountPath: /var/lib/docker/containers
    #  readOnly: true
    #- name: pods
    #  mountPath: /var/log/pods
    #  readOnly: true
{{- end }}
