[extend]

useDefault = true

[[allowlists]]

description = "global allow list"
paths = [
  "terraform-customer.auto.tfvars",
  "cluster/overlay/",
  ".terraform/",
  ".output.json",
  ".overlay.output.json",
  ".overlay.tfvars.json",
  ".kubeconfig",
  ".kustomize_build.yaml",
  "terraform.log",
  "values.yaml"
]
