apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
mountOptions:
- tls
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  basePath: /dynamic_provisioning
  directoryPerms: "700"
  gidRangeEnd: "2000"
  gidRangeStart: "1000"
  provisioningMode: efs-ap
