apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog
  namespace: flux-system
spec:
  chart:
    spec:
      chart: datadog
      version: 3.x
      sourceRef:
        kind: HelmRepository
        name: datadog
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: datadog
  storageNamespace: datadog
  targetNamespace: datadog
  values:
    datadog:
      #clusterName:
      #apiKey:

      otlp:
        receiver:
          protocols:
            http:
              enabled: true

      kubelet:
        tlsVerify: false

      apm:
        portEnabled: true
        socketEnabled: true

      orchestratorExplorer:
        enabled: true
        container_scrubbing:
          enabled: true

      processAgent:
        enabled: true

    clusterAgent:
      resources:
        limits:
          cpu: 200m
          memory: 800Mi

    agents:
      #customAgentConfig:
      #  apm_config:
      #    obfuscation:
      #      credit_cards:
      #        enabled: false
      #        luhn: false
      containers:
        agent:
          #env:
          #- name: DD_APM_OBFUSCATION_CREDIT_CARDS_ENABLED
          #  value: "false"
          resources:
            #requests:
            #  cpu: 100m
            #  memory: 256Mi
            limits:
              cpu: 200m
              memory: 768Mi
        processAgent:
          resources:
            #requests:
            #  cpu: 100m
            #  memory: 256Mi
            limits:
              cpu: 200m
              memory: 768Mi

      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: "100%"

      #priorityClassCreate: true
      priorityClassName: system-cluster-critical

      podSecurity:
        privileged: true
        podSecurityPolicy:
          create: true
        ## OKD
        #securityContextConstraints:
        #  create: true
        #seLinuxContext:
        #  rule: MustRunAs
        #  seLinuxOptions:
        #    user: "system_u"
        #    role: "system_r"
        #    type: "spc_t"
        #    level: "s0"

    kube-state-metrics:
      podSecurityPolicy:
        enabled: true
      serviceAccount:
        create: true
