apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ecr-credentials-sync
      sourceRef:
        kind: HelmRepository
        name: getupcloud
      version: "~> 2"
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 10m
  releaseName: ecr-credentials-sync
  storageNamespace: flux-system
  targetNamespace: flux-system
  values:
    secret:
      name: ecr-credentials
