apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
      version: "~> 1.36"
  dependsOn:
  - name: monitoring
  install:
    createNamespace: true
    crds: CreateReplace
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    disableWait: false
    remediation:
      retries: -1
  interval: 10m
  releaseName: flagger
  values:
    # Choose one provider from cluster/overlay/flagger.yaml
