apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
  name: kubed
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubed
      sourceRef:
        kind: HelmRepository
        name: getupcloud
      version: v0.13.2
  install:
    createNamespace: false
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 5m
  releaseName: kubed
  storageNamespace: kube-system
  targetNamespace: kube-system
  values: {}
