apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  chart:
    spec:
      chart: opencost
      sourceRef:
        kind: HelmRepository
        name: opencost
      version: "~> 1.43.0"
  dependsOn:
  - name: monitoring
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 10m
  releaseName: opencost
  storageNamespace: opencost
  targetNamespace: opencost
  values:
    opencost:
      #cloudIntegrationSecret: cloud-costs
      cloudCost:
        enabled: false
      customPricing:
        enabled: true
      dataRetention:
        dailyResolutionDays: 180
      exporter:
        csv_path: /mnt/export/usage.json
        persistence:
          enabled: true
          size: 10Gi
          accessMode: "ReadWriteOnce"
      prometheus:
        internal:
          serviceName: monitoring-kube-prometheus-prometheus
          namespaceName: monitoring
          port: 9090
      metrics:
        serviceMonitor:
          enabled: true
