apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-shop-demo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: opentelemetry-demo
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: "0.29.x"
  dependsOn:
  - name: otel-operator
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 10m
  releaseName: otel-shop-demo
  storageNamespace: otel-shop-demo
  targetNamespace: otel-shop-demo
  values: {}
