apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: "~> 6.9"
  install:
    createNamespace: true
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 0
  upgrade:
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 0
  interval: 24h
  releaseName: podinfo
  storageNamespace: podinfo
  targetNamespace: podinfo
  values:
    service:
      enabled: true
    serviceMonitor:
      enabled: true
      interval: 1m
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 10m
        memory: 32Mi
