apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-agent
  namespace: flux-system
spec:
  chart:
    spec:
      chart: teleport-kube-agent
      version: 17.7.4
      sourceRef:
        kind: HelmRepository
        name: teleport
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 10m
  releaseName: teleport-agent
  storageNamespace: getup
  targetNamespace: getup
  values:
    proxyAddr: getup.teleport.sh:443

    podSecurityPolicy:
      enabled: false
