apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "~> 1.10.3"
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 10m
  releaseName: tempo
  storageNamespace: monitoring
  targetNamespace: monitoring
  values:
    persistence:
      enabled: true
      size: 10Gi

    serviceMonitor:
      enabled: true
      interval: 60s

    tempo:
      multitenancyEnabled: false
      retention: 168h
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://monitoring-kube-prometheus-prometheus:9090/api/v1/write"
      storage:
        trace:
          empty_tenant_deletion_enabled: true
          backend: s3
