{{- if and .Values.manifests .Values.awsLoadBalancerController.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "aws-load-balancer-controller" "values" .Values.awsLoadBalancerController.extraValues) | nindent 2 }}
  values:
    clusterName: {{ include "clusterName" . }}

    replicaCount: 1

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.awsLoadBalancerController.aws_load_balancer_controller_iam_role_arn }}
---
{{ include "fluxValuesFromData" (dict "secretName" "aws-load-balancer-controller" "values" .Values.awsLoadBalancerController.extraValues) }}
{{- end }}