{{- if and .Values.mode.overlay .Values.certManager.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.certManager.certManagerIamRoleArn }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  values:
    acme_email: {{ .Values.certManagerConfig.certmanagerAcmeEmail }}
    # cluster_issuer_dns01:
    #   aws_access_key_id: ""
    #   aws_region: ""
    #   aws_zones: ""
    #   enabled: false
{{- end }}
