{{- if and .Values.manifests .Values.ecrCredentialsSync.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "ecr-credentials-sync" "values" .Values.ecrCredentialsSync.extraValues) | nindent 2 }}
  values:
    #secret:
    #  namespaceLabelSelector:
    #    ecr-credentials: "true"

    awsAccountId: {{ .Values.awsAccountId | quote }}

    ecr:
      region: {{ .Values.awsRegion }}

    serviceAccount:
      create: true
      name: "ecr-credentials-sync"
      roleArn: {{ .Values.ecrCredentialsSync.ecrCredentialsSyncIamRoleArn }}
---
{{ include "fluxValuesFromData" (dict "secretName" "ecr-credentials-sync" "values" .Values.ecrCredentialsSync.extraValues) }}
{{- end }}
