{{- if and .Values.manifests .Values.externalSecrets.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "external-secrets" "values" .Values.externalSecrets.extraValues) | nindent 2}}
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.externalSecrets.awsEsoIamRoleArn }}
---
{{ include "fluxValuesFromData" (dict "secretName" "external-secrets" "values" .Values.externalSecrets.extraValues) }}
{{- end }}

{{- if and .Values.manifests .Values.externalSecretsConfig.enabled }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "external-secrets-config" "values" .Values.externalSecretsConfig.extraValues) | nindent 2}}
  values:
    template-store:
      metadata:
        name: {{ include "clusterName" . }}
      spec:
        provider:
          aws:
            region: {{ .Values.awsRegion }}
---
{{ include "fluxValuesFromData" (dict "secretName" "external-secrets-config" "values" .Values.externalSecretsConfig.extraValues) }}
{{- end }}
