{{- if and .Values.mode.overlay .Values.externalSecretsOperator.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "external-secrets-operator" "values" .Values.externalSecretsOperator.extraValues) | nindent 2}}
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.externalSecretsOperator.externalSecretsOperatorIamRoleArn }}
---
{{ include "fluxValuesFromData" (dict "secretName" "external-secrets-operator" "values" .Values.externalSecretsOperator.extraValues) }}
{{- end }}
