{{- if and .Values.mode.overlay .Values.externalSecretsConfig.enabled }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "external-secrets-config" "values" .Values.externalSecretsConfig.extraValues) | nindent 2}}
  values:
    template-store:
      metadata:
        name: {{ include "clusterName" . }}
      spec:
        provider:
          aws:
            region: {{ .Values.eks.eksAwsRegion }}
---
{{ include "fluxValuesFromData" (dict "secretName" "external-secrets-config" "values" .Values.externalSecretsConfig.extraValues) }}
{{- end }}

