{{- if and .Values.mode.overlay .Values.loki.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "loki" "values" .Values.loki.extraValues) | nindent 2 }}
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.loki.lokiIamRoleArn }}
    loki:
      storage:
        type: s3
        s3:
          region: {{ .Values.eks.eksAwsRegion }}
        bucketNames:
          chunks: {{ .Values.loki.lokiS3BucketName }}
          ruler: {{ .Values.loki.lokiS3BucketName }}
---
{{ include "fluxValuesFromData" (dict "secretName" "loki" "values" .Values.loki.extraValues) }}
{{- end }}
