{{- if and .Values.manifests .Values.opencost.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "opencost" "values" .Values.opencost.extraValues) | nindent 2 }}
  values:
    opencost:
      customPricing:
        provider: aws
        costModel:
          awsSpotDataRegion: {{ .Values.aws_region }}
          awsSpotDataBucket: {{ .Values.opencost_spot_datafeed_bucket_name }}
          awsSpotDataPrefix: {{ .Values.opencost_spot_datafeed_bucket_prefix }}
          projectID: {{ .Values.aws_account_id | quote }}
      exporter:
        defaultClusterId: {{ .Values.cluster_name }}
        persistence:
          storageClass: {{ .Values.default_storage_class_name }}
    serviceAccount:
      name: opencost
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.opencost_iam_role_arn }}
---
{{ include "fluxValuesFromData" (dict "secretName" "opencost" "values" .Values.opencost.extraValues) }}
{{- end }}