{{- if and .Values.mode.overlay .Values.opencost.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "opencost" "values" .Values.opencost.extraValues) | nindent 2 }}
  values:
    opencost:
      customPricing:
        provider: aws
        costModel:
          awsSpotDataRegion: {{ .Values.eks.eksAwsRegion }}
          awsSpotDataBucket: {{ .Values.opencost.opencostSpotDatafeedBucketName }}
          awsSpotDataPrefix: {{ .Values.opencost.opencostSpotDatafeedBucketPrefix }}
          projectID: {{ .Values.eks.eksAwsAccountId | quote }}
      exporter:
        defaultClusterId: {{ include "clusterName" . }}
        persistence:
          storageClass: {{ include "defaultStorageClassName" . }}
    serviceAccount:
      name: opencost
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.opencost.opencostIamRoleArn }}
---
{{ include "fluxValuesFromData" (dict "secretName" "opencost" "values" .Values.opencost.extraValues) }}
{{- end }}
