{{- if and .Values.manifests .Values.teleportAgent.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-agent
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "teleport-agent" "values" .Values.teleportAgent.extraValues) | nindent 2 }}
  values:
    authToken: {{ .Values.teleportAgent.teleportAuthToken }}
    kubeClusterName: {{ .Values.customerName }}-{{ include "clusterName" . }}

    labels:
      customer: {{ .Values.customerName }}
      region: {{ .Values.awsRegion }}
      sla: {{ .Values.clusterSla }}
---
{{ include "fluxValuesFromData" (dict "secretName" "teleport-agent" "values" .Values.teleportAgent.extraValues) }}
{{- end }}
