{{- if and .Values.manifests .Values.tempo.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "tempo" "values" .Values.tempo.extraValues) | nindent 2 }}
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.tempoIamRoleArn }}
    tempo:
      storage:
        trace:
          s3:
            bucket: {{ .Values.tempoS3BucketName }}
            region: {{ .Values.awsRegion }}
            endpoint: s3.dualstack.{{ .Values.awsRegion }}.amazonaws.com
---
{{ include "fluxValuesFromData" (dict "secretName" "tempo" "values" .Values.tempo.extraValues) }}
{{- end }}
