{{- if and .Values.manifests .Values.velero.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  {{- include "fluxValuesFrom" (dict "secretName" "velero" "values" .Values.velero.extraValues) | nindent 2 }}
  values:
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.10.0
      volumeMounts:
      - mountPath: /target
        name: plugins

    configuration:
      defaultBackupStorageLocation:
      - aws: default
      backupStorageLocation:
      - provider: aws
        name: default
        default: true
        prefix: velero/{{ template "clusterLongName" . }}
        bucket: {{ .Values.velero.velero_s3_bucket_name }}
        config:
          region: {{ .Values.aws_region }}
      {{- if .Values.velero.extraBackupStorageLocations }}
      {{- .Values.velero.extraBackupStorageLocations | nindent 6 }}
      {{- end }}

      volumeSnapshotLocation:
      - provider: aws
        name: default
        default: true
        config:
          region: {{ .Values.aws_region }}
      {{- if .Values.velero.extraVolumeSnapshotLocation }}
      {{- .Values.velero.extraVolumeSnapshotLocation | nindent 6 }}
      {{- end }}

    serviceAccount:
      server:
        create: true
        name: velero
        annotations:
          eks.amazonaws.com/role-arn: {{ .Values.velero.velero_iam_role_arn }}
---
{{ include "fluxValuesFromData" (dict "secretName" "velero" "values" .Values.velero.extraValues) }}
{{- end }}