apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  values:
    clusterName: #output:{cluster_name}
    vpcId: #output:{eks_cluster_vpc_id}

    replicaCount: 1

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: #output:{eks_aws_load_balancer_controller_iam_role_arn}
