apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
parameters:
  #basePath: /dynamic_provisioning
  #directoryPerms: "700"
  #gidRangeEnd: "2000"
  #gidRangeStart: "1000"
  #provisioningMode: efs-ap
  fileSystemId: #output:{overlay["aws_efs_filesystem_id"]}
