apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: #output:{cert_manager_iam_role_arn}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  values:
    acme_email: #output:{overlay["certmanager_acme_email"]}
    # cluster_issuer_dns01:
    #   aws_access_key_id: ""
    #   aws_region: ""
    #   aws_zones: ""
    #   enabled: false
