apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
spec:
  values:
    secret:
      annotations:
        kubed.appscode.com/sync: ""

    #  namespaceLabelSelector:
    #    ecr-credentials: "true"

    awsAccountId: #output:"{aws_account_id}"

    ecr:
      region: #output:{aws_region}

    serviceAccount:
      create: true
      name: "ecr-credentials-sync"
      roleArn: #output:{ecr_credentials_sync_iam_role_arn}
