apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: #output:{loki_iam_role_arn}
    loki:
      storage:
        type: s3
        s3:
          region: #output:{aws_region}
        bucketNames:
          chunks: #output:{loki_s3_bucket_name}
          ruler: #output:{loki_s3_bucket_name}
    write:
      nodeSelector:
        karpenter.sh/capacity-type: on-demand
    read:
      nodeSelector:
        karpenter.sh/capacity-type: on-demand
    resultsCache:
      nodeSelector:
        karpenter.sh/capacity-type: on-demand
    backend:
      nodeSelector:
        karpenter.sh/capacity-type: on-demand
    chunksCache:
      nodeSelector:
        karpenter.sh/capacity-type: on-demand
