apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  values:
    opencost:
      customPricing:
        provider: aws
        costModel:
          awsSpotDataRegion: #output:{aws_region}
          awsSpotDataBucket: #output:{opencost_spot_datafeed_bucket_name}
          awsSpotDataPrefix: #output:{opencost_spot_datafeed_bucket_prefix}
          projectID: #output:"{aws_account_id}"
      exporter:
        defaultClusterId: #output:{cluster_name}
        persistence:
          storageClass: #output:{default_storage_class_name}
    serviceAccount:
      name: opencost
      annotations:
        eks.amazonaws.com/role-arn: #output:{opencost_iam_role_arn}
