apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-demo
  namespace: flux-system
spec:
  values:
    literal-ingress:
      spec:
        rules:
        - host: otel-demo.example.com
          http:
            paths:
            - backend:
                service:
                  name: otel-demo-frontend
                  port:
                    number: 80
              path: /
              pathType: Prefix
