apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      className: #output:{overlay["default_ingress_class_name"]}
      hosts:
      - host: podinfo.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
      - secretName: podinfo-tls
        hosts:
        - podinfo.example.com

