apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  values:
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.10.0
      volumeMounts:
      - mountPath: /target
        name: plugins

    credentials:
      useSecret: false # required to use IRSA

    configuration:
      defaultBackupStorageLocation:
      - aws: default
      backupStorageLocation:
      - provider: aws
        name: default
        default: true
        prefix: #output:velero/{cluster_name}-{aws_region}
        bucket: #output:{velero_s3_bucket_name}
        config:
          region: #output:{aws_region}

      defaultVolumeSnapshotLocations:
      - aws: default
      volumeSnapshotLocation:
      - provider: aws
        name: default
        default: true
        config:
          region: #output:{aws_region}

    serviceAccount:
      server:
        create: true
        name: velero
        annotations:
          eks.amazonaws.com/role-arn: #output:{velero_iam_role_arn}
