{{ if .Values.mode.kustomization -}}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flux-system
{{- if .Values.mode.apps }}
- ../apps/
{{- end }}
- base.yaml
{{- with .Values.extraResources }}
{{ .Values.extraResources | toYaml }}
{{- end }}

patches:
- path: overlay.yaml
{{- with .Values.extraPatches }}
{{ .Values.extraPatches | toYaml }}
{{- end }}

{{- end -}}
